function plainIdentifier(name, label) {
  if (!/^[A-Za-z_$][\w$]*$/.test(name))
    throw new Error(
      `${label} '${name}' uses an escaped or unsupported identifier. Rename it to a plain SystemVerilog identifier before generating a starter testbench.`,
    );
  return name;
}

function isClock(name) {
  return /^(clk|clock|.*_clk|clk_.*)$/i.test(name);
}

function isReset(name) {
  return /^(rst|reset|rst_n|reset_n|nreset|n_rst)$/i.test(name);
}

function isActiveLowReset(name) {
  return /(_n$|^n(?:reset|_rst)$)/i.test(name);
}

function declaration(port) {
  const width = port.bits?.length || 1;
  const range = width > 1 ? ` [${width - 1}:0]` : '';
  return `    logic${range} ${plainIdentifier(port.name, 'Port')};`;
}

function generateStarterTestbench(netlist, moduleName, options = {}) {
  const module = netlist.modules?.[moduleName];
  if (!module)
    throw new Error(`Module '${moduleName}' was not found in the current Yosys netlist.`);
  plainIdentifier(moduleName, 'Module');
  const ports = Object.entries(module.ports || {}).map(([name, port]) => ({ name, ...port }));
  for (const port of ports) plainIdentifier(port.name, 'Port');
  const inputs = ports.filter((port) => port.direction === 'input');
  const clocks = inputs.filter((port) => isClock(port.name));
  const resets = inputs.filter((port) => isReset(port.name));
  const stimulusInputs = inputs.filter((port) => !clocks.includes(port) && !resets.includes(port));
  const testbenchName = `${moduleName}_tb`;
  const clockPeriod = Number.isFinite(Number(options.clockPeriod))
    ? Math.max(2, Math.min(1000000, Math.round(Number(options.clockPeriod))))
    : 10;
  const resetDuration = Number.isFinite(Number(options.resetDuration))
    ? Math.max(0, Math.min(1000000, Math.round(Number(options.resetDuration))))
    : 12;
  const finishTime = Number.isFinite(Number(options.finishTime))
    ? Math.max(resetDuration + 1, Math.min(100000000, Math.round(Number(options.finishTime))))
    : 80;
  const inputNames = new Set(stimulusInputs.map((port) => port.name));
  const steps = Array.isArray(options.steps)
    ? options.steps
        .map((step) => ({
          time: Math.round(Number(step.time)),
          signal: plainIdentifier(String(step.signal || ''), 'Stimulus signal'),
          value: String(step.value || '').trim(),
        }))
        .filter(
          (step) =>
            Number.isFinite(step.time) &&
            step.time >= resetDuration &&
            step.time <= finishTime &&
            inputNames.has(step.signal) &&
            /^(?:\d+|'[bdho][0-9a-fxz_]+|\d+'[bdho][0-9a-fxz_]+)$/i.test(step.value),
        )
        .sort((a, b) => a.time - b.time)
    : [];
  const stimulusLines = [];
  if (steps.length) {
    let previous = resetDuration;
    for (const step of steps) {
      stimulusLines.push(
        `        #${Math.max(0, step.time - previous)} ${step.signal} = ${step.value};`,
      );
      previous = step.time;
    }
    stimulusLines.push(`        #${Math.max(1, finishTime - previous)};`);
  } else
    stimulusLines.push(
      ...stimulusInputs.map((port) => `        #10 ${port.name} = '1;`),
      ...stimulusInputs.map((port) => `        #10 ${port.name} = '0;`),
      '        #20;',
    );
  const lines = [
    '`timescale 1ns/1ps',
    '',
    `// Starter testbench generated by OpenBench from Yosys metadata for ${moduleName}.`,
    '// Edit the marked stimulus section as your design grows.',
    `module ${testbenchName};`,
    ...ports.map(declaration),
    '',
    `    ${moduleName} dut (`,
    ...ports.map(
      (port, index) =>
        `        .${port.name}(${port.name})${index === ports.length - 1 ? '' : ','}`,
    ),
    '    );',
    '',
    ...clocks.flatMap((port) => [
      `    initial ${port.name} = 1'b0;`,
      `    always #${Math.max(1, Math.round(clockPeriod / 2))} ${port.name} = ~${port.name};`,
      '',
    ]),
    '    initial begin',
    `        $dumpfile("${moduleName}.vcd");`,
    `        $dumpvars(0, ${testbenchName});`,
    ...resets.map(
      (port) => `        ${port.name} = 1'b${isActiveLowReset(port.name) ? '0' : '1'};`,
    ),
    ...stimulusInputs.map((port) => `        ${port.name} = '0;`),
    resets.length
      ? `        #${resetDuration}; // Hold reset across at least one clock edge.`
      : '        #2;',
    ...resets.map(
      (port) => `        ${port.name} = 1'b${isActiveLowReset(port.name) ? '1' : '0'};`,
    ),
    '',
    steps.length
      ? '        // Visual stimulus steps generated by OpenBench. Edit freely.'
      : '        // TODO: Replace this basic pulse with stimulus meaningful to your design.',
    ...stimulusLines,
    '        $finish;',
    '    end',
    'endmodule',
    '',
  ];
  return {
    moduleName,
    testbenchName,
    fileName: `${testbenchName}.sv`,
    content: lines.join('\n'),
    detected: {
      clocks: clocks.map((port) => port.name),
      resets: resets.map((port) => port.name),
      stimulusInputs: stimulusInputs.map((port) => port.name),
    },
  };
}

module.exports = { generateStarterTestbench, isActiveLowReset, isClock, isReset };
