function plainIdentifier(name, label) {
  if (!/^[A-Za-z_$][\w$]*$/.test(name)) throw new Error(`${label} '${name}' uses an escaped or unsupported identifier. Rename it to a plain SystemVerilog identifier before generating a starter testbench.`);
  return name;
}

function isClock(name) {
  return /^(clk|clock|.*_clk|clk_.*)$/i.test(name);
}

function isReset(name) {
  return /^(rst|reset|rst_n|reset_n|nreset|n_rst)$/i.test(name);
}

function isActiveLowReset(name) {
  return /(_n$|^n(?:reset|_rst)$)/i.test(name);
}

function declaration(port) {
  const width = port.bits?.length || 1;
  const range = width > 1 ? ` [${width - 1}:0]` : '';
  return `    logic${range} ${plainIdentifier(port.name, 'Port')};`;
}

function generateStarterTestbench(netlist, moduleName) {
  const module = netlist.modules?.[moduleName];
  if (!module) throw new Error(`Module '${moduleName}' was not found in the current Yosys netlist.`);
  plainIdentifier(moduleName, 'Module');
  const ports = Object.entries(module.ports || {}).map(([name, port]) => ({ name, ...port }));
  for (const port of ports) plainIdentifier(port.name, 'Port');
  const inputs = ports.filter((port) => port.direction === 'input');
  const clocks = inputs.filter((port) => isClock(port.name));
  const resets = inputs.filter((port) => isReset(port.name));
  const stimulusInputs = inputs.filter((port) => !clocks.includes(port) && !resets.includes(port));
  const testbenchName = `${moduleName}_tb`;
  const lines = [
    '`timescale 1ns/1ps',
    '',
    `// Starter testbench generated by OpenBench from Yosys metadata for ${moduleName}.`,
    '// Edit the marked stimulus section as your design grows.',
    `module ${testbenchName};`,
    ...ports.map(declaration),
    '',
    `    ${moduleName} dut (`,
    ...ports.map((port, index) => `        .${port.name}(${port.name})${index === ports.length - 1 ? '' : ','}`),
    '    );',
    '',
    ...clocks.flatMap((port) => [`    initial ${port.name} = 1'b0;`, `    always #5 ${port.name} = ~${port.name};`, '']),
    '    initial begin',
    `        $dumpfile("${moduleName}.vcd");`,
    `        $dumpvars(0, ${testbenchName});`,
    ...resets.map((port) => `        ${port.name} = 1'b${isActiveLowReset(port.name) ? '0' : '1'};`),
    ...stimulusInputs.map((port) => `        ${port.name} = '0;`),
    resets.length ? '        #12; // Hold reset across at least one clock edge.' : '        #2;',
    ...resets.map((port) => `        ${port.name} = 1'b${isActiveLowReset(port.name) ? '1' : '0'};`),
    '',
    '        // TODO: Replace this basic pulse with stimulus meaningful to your design.',
    ...stimulusInputs.map((port) => `        #10 ${port.name} = '1;`),
    ...stimulusInputs.map((port) => `        #10 ${port.name} = '0;`),
    '        #20;',
    '        $finish;',
    '    end',
    'endmodule',
    '',
  ];
  return { moduleName, testbenchName, fileName: `${testbenchName}.sv`, content: lines.join('\n'), detected: { clocks: clocks.map((port) => port.name), resets: resets.map((port) => port.name), stimulusInputs: stimulusInputs.map((port) => port.name) } };
}

module.exports = { generateStarterTestbench, isActiveLowReset, isClock, isReset };
